name: Automate Animal Facts

on:
  push:
    branches:
      - main

jobs:
  generate_and_update_facts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Generate Facts
      run: python generate_facts_about_animals.py

    - name: Replace Placeholders
      run: python replace_placeholders.py

    - name: Commit Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update animal facts [skip ci]"

    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
